version: 2.0

jobs:
  Python_3.9:
    docker:
      - image: cimg/python:3.9
    steps: &steps
      - checkout
      - run: python --version ; pip3 --version ; pwd ; ls
      - run: pip3 install -e .["dev"]
      - run: make reformat
      - run: pytest
  Python_3.10:
    docker:
      - image: cimg/python:3.10
    steps: *steps
  Python_3.11:
    docker:
      - image: cimg/python:3.11
    steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - Python_3.9
      - Python_3.10
      - Python_3.11
